services:
  - type: web
    name: chatgpt-api-proxy
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: sk-... (albo ustaw ręcznie w panelu Render)
